name: Listwell
options:
  bundleIdPrefix: com.listwell
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: "7.0.0"

targets:
  Listwell:
    type: application
    platform: iOS
    sources:
      - path: Listwell
    settings:
      base:
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: Listwell/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.listwell.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
        SWIFT_EMIT_LOC_STRINGS: true
    dependencies:
      - package: Kingfisher
    scheme:
      testTargets:
        - ListwellTests

  ListwellTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ListwellTests
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: true
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Listwell.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Listwell"
    dependencies:
      - target: Listwell
